"""
Apex python app
Reads CSP additional telemetry data (aero, dampers) and shares it with the Lua app via ac.ext_storeLua()
"""

import ac, acsys


appName = "apex"

def acMain(ac_version):
    return appName

ac.log('Apex python buffer initialized')


# About rate update =======================================================================================
#  
# The rate "rate" should match the highest sampling rate offered in the LUA app's (cfg/app.lua -> DATA_RATES)
# for example, if app.lua offers { 25, 30, 50 }, set this rate to 50Hz (0.02).
#
# There is no harm in Python running faster than Lua, it's perfectly safe to leave it running 
# at max frequency (150Hz). The Lua app will simply fetch the most up-to-date data from shared memory 
# when it polls ignoring the extra updates generated by Python.

# Rate limiters:
#
# 10Hz  = 0.1 (for aero only)
# 25Hz  = 0.04
# 30Hz  = 0.033
# 50Hz  = 0.02
# 150Hz = 0.0065

deltaL = 1
rate = 0.0065

def acUpdate(dt):
    global deltaL

    if deltaL + dt > rate:
        vals = [
            # drag, downforce front and rear
            ac.ext_getDrag(),
            ac.ext_getDownforce(0),
            ac.ext_getDownforce(1),
            # damper travel (mm): FL, FR, RL, RR, HF, HR
            ac.ext_getDamperTravel(0) * 1000,
            ac.ext_getDamperTravel(1) * 1000,
            ac.ext_getDamperTravel(2) * 1000,
            ac.ext_getDamperTravel(3) * 1000,
            ac.ext_getDamperTravel(4) * 1000,
            ac.ext_getDamperTravel(5) * 1000
        ]
        # -- store for lua app to be read via "ac.load('apex.pySerialData')"
        ac.ext_storeLua('apex.pySerialData', ",".join(map(str, vals)))
        
        deltaL = 0
    
    deltaL += dt
